# Generated by Django 3.0.3 on 2020-02-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20200208_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
