# Generated by Django 3.0.3 on 2020-02-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20200208_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
