# Generated by Django 3.0.3 on 2020-02-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
