# Generated by Django 3.0.3 on 2020-02-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.TextField(null=True, unique=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FieldSchema',
        ),
        migrations.DeleteModel(
            name='ModelSchema',
        ),
    ]
