# Generated by Django 3.0.3 on 2020-02-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_auto_20200208_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='category',
            field=models.TextField(default='shipments'),
        ),
        migrations.AddField(
            model_name='shipments',
            name='shipmentData',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='shipments',
            name='shipmentItems',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='shipments',
            name='transportId',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='data',
            field=models.TextField(default=None),
        ),
    ]
