# Generated by Django 3.0.3 on 2020-02-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_auto_20200208_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipments',
            old_name='shipmentData',
            new_name='shipmentDate',
        ),
    ]
