# Generated by Django 3.0.3 on 2020-02-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_auto_20200208_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='category',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='shipmentDate',
            field=models.TextField(default=0),
        ),
    ]
