# Generated by Django 3.0.3 on 2020-02-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_auto_20200208_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='shipmentDate',
            field=models.TextField(),
        ),
    ]
