# Generated by Django 3.0.3 on 2020-02-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_auto_20200208_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipments',
            name='id',
        ),
        migrations.AlterField(
            model_name='shipments',
            name='data',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='shipmentId',
            field=models.TextField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
